### ISSUE TITLE
Deploy the api with the site as a function?

### ISSUE THREAD

**Issue by ForsakenHarmony** [team-underscore/revealURL_CLIENT#7]
Seems like you're using something deployed to heroku to resolve the urls instead of having it in this repo

**Comment by Gaurav-Shankar** [comment]
Hey @ForsakenHarmony , thanks for your interest.
We do have plans to move the backend to this repo as well. Most probably we'll be doing it along with the release of chrome extension coming monday.
Keep an eye on it. :)
